[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "MUCHOSpec-ETC"
version = "0.1.0"
description = "Exposure Time Calculator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=8.0.1",
    "fastapi[standard]>=0.141.1",
    "scipy==1.14.1",
    "synphot>=1.7.0",
]


[project.scripts]
start-microservice = "MUCHOSpec_ETC.main:main"
